package ru.chimchima.repository

object AntihypeRepository : SongRepository() {
    override val songs = NemimohypeRepository.songs + HypeTrainRepository.songs + AntihypeTrainRepository.songs
}

object NemimohypeRepository : SongRepository() {
    override val songs = listOf(
        "Интро" to "https://youtu.be/YemQ_lUWR4Y" to true,
        "Трое в лодке (feat. Петрик Путяха)" to "https://youtu.be/tYQ4vXTboik" to true,
        "Ретвит от Мирона (feat. Букер Д. Фред)" to "https://youtu.be/6ZQ8eI7jjtM" to false,
        "Берлиоз" to "https://youtu.be/J6YmF9kSY1A" to true,
        "Надежда Грайма" to "https://youtu.be/UXr4sxRB0-g" to true,
        "Grime Hate" to "https://youtu.be/UBRSbL73S-8" to true,
        "Пиу-пиу" to "https://youtu.be/Ie-3LU06I9w" to false,
        "Контрольный выстрел" to "https://youtu.be/Z4yaDBnk5G8" to true,
        "Бытиё есть Панчлайн (feat. Вандальский)" to "https://youtu.be/6KOMWN6HSGc" to false,
        "Умный парень (feat. Vs94ski)" to "https://youtu.be/2heMxce0ZDc" to true,
        "#НЕМИМОХАЙПА" to "https://youtu.be/LYW35triFG8" to false,
        "Мой хайп" to "https://youtu.be/1JjPdns7RCk" to false,
        "Mf Dron (feat. Young Gipsy)" to "https://youtu.be/-VOu1zyAKEs" to false,
        "Sadwave (feat. Кореш)" to "https://youtu.be/aKIHE6Ndpj0" to false,
        "Верим в Перуна (Руна нам дана) (feat. Zoo In Space)" to "https://youtu.be/cK2ZG0bKEk4" to false,
        "Отдыхайте в Крыму! (feat. Вандальский)" to "https://youtu.be/XAUJpQxQTzw" to false,
        "Не забывай! (feat. Вандальский)" to "https://youtu.be/tFb4D6WpC-g" to true,
        "Страх и ненависть в Ленинграде" to "https://youtu.be/BAuDw9mTvXo" to false,
        "Парад калек (feat. MF Док, Саша Маставой & Грязный Луи)" to "https://youtu.be/z_9E1rX4r4c" to false,
        "ЛГБТ Anthem (feat. ВИА Молодые Аллахи)" to "https://youtu.be/dsl690CPU_8" to false,
        "Воскресение (feat. Овсянкин)" to "https://youtu.be/ASFBl5HVJkM" to false,
        "Культурное похмелье (feat. Саша)" to "https://youtu.be/FVhvcs16tjg" to false,
        "Смерть на рейве" to "https://youtu.be/_XVnfnkRy40" to false,
        "Апокалипсис" to "https://youtu.be/zUPMEpTdlcY" to false,
        "Рагнарок (feat. Вандальский)" to "https://youtu.be/2pMMx4ryGD8" to false,
        "Моя тюрьма (feat. Саша Дискотека)" to "https://youtu.be/oBh51kpEzBI" to true,
        "Паук (feat. Vs94ski)" to "https://youtu.be/e2RqDHziN6k" to true,
        "Outro" to "https://youtu.be/dokLpx5UaA0" to true
    ).toSongs()
}

object HypeTrainRepository : SongRepository() {
    override val songs = listOf(
        "HYPEINTRO" to "https://youtu.be/jzVuLFXIuJg" to true,
        "Макароны (feat. КИЧ)" to "https://youtu.be/YaJXdiwXei0" to true,
        "#FREEYUNGTRAPPA (feat. Аббалбиск)" to "https://youtu.be/iXdvCdR-Lj4" to false,
        "Giger (feat. Аббалбиск)" to "https://youtu.be/zYwqsf27yV4" to false,
        "Облажает (feat. Unda Scope)" to "https://youtu.be/Er4mT37feuA" to false,
        "FUCKTRAP (feat. Маки)" to "https://youtu.be/GhUnTUkM85M" to true,
        "Вейп-вейп-вейп (feat. Лсп, Young P&h, Эхопрокуренныхподъездов, Заебатсу & Booker)" to "https://youtu.be/dyqbYEQ_a6g" to true,
        "Гоша Рубчинский (feat. Сд, Zoo In Space, Booker & Овсянкин)" to "https://youtu.be/zYcvQMgxOWU" to true,
        "Сэймяу Game (feat. Овсянкин & Fallen MC)" to "https://youtu.be/ienV8yg2P1w" to false,
        "Grime в России" to "https://youtu.be/MtEJEhvSJuY" to false,
        "Сука не нужна (feat. Хип-Хоп Одинокой Старухи & Овсянкин)" to "https://youtu.be/8wY5HNK04u0" to false,
        "Стикербой (feat. Стеефан)" to "https://youtu.be/qKROw2UKxL8" to false,
        "Покемоны мои (feat. Монеточка & Овсянкин)" to "https://youtu.be/kR8Um8DFf-g" to false,
        "Районная (feat. Майти Ди, Edik_Kingsta & Halloween)" to "https://youtu.be/sMqTfFzeuj8" to false,
        "Вне игры (feat. СД, Саша & Morralles) [Long Mix]" to "https://youtu.be/wziD6qEi29U" to false,
        "Крокодил (feat. СД, Монк & Овсянкин)" to "https://youtu.be/rKyf1TSN-5I" to false,
        "Боевой шок (feat. Ленина Пакет)" to "https://youtu.be/2c77WvotQI8" to false,
        "Корона (feat. Palach)" to "https://youtu.be/ldq2ydAYDRo" to false,
        "В футболке Бабангида (feat. Овсянкин)" to "https://youtu.be/YqxL1ONGU_0" to true,
        "Реп-мент (feat. ΨBOY & Человек-Спам)" to "https://youtu.be/RyQF6f7CD40" to false,
        "Вичхаус лобня-2 (feat. Мц Лучник)" to "https://youtu.be/E2hrOHiATRU" to false,
        "Дурь-трава (feat. MF Док & Edik_Kingsta)" to "https://youtu.be/GlcizCN9ztw" to true,
        "Весна (feat. Паша Техник, СД, MF Док & Овсянкин)" to "https://youtu.be/7zn-muE2sZE" to false,
        "Абамка (feat. Саша Скул & Овсянкин)" to "https://youtu.be/dqOmJx--BfE" to false,
        "Техника молодежи (feat. Сугат & Некий Шура)" to "https://youtu.be/SFDRvV1Y1Vs" to false,
        "Сиплота (feat. Сугат, Катровасер & Тот Самый Коля)" to "https://youtu.be/-0uBovKLTM0" to false,
        "Эльдорадо (feat. Абуя Ко & Саша)" to "https://youtu.be/rHnRrEzislU" to false,
        "Фонк гука (feat. MF Док)" to "https://youtu.be/gZ05YMp7CRw" to false,
        "Антихайп (feat. Майти Ди, Zoo In Space & Lokos)" to "https://youtu.be/evClbzpnQlY" to false,
        "Старый отель (feat. Саша Маставой & Катровасер)" to "https://youtu.be/_NIEvLE5Ukg" to false
    ).toSongs()
}

object AntihypeTrainRepository : SongRepository() {
    override val songs = listOf(
        "Antihypeintro" to "https://youtu.be/x0lfEcgjjKE",
        "Двуглавый орёл" to "https://youtu.be/dh_TPlOFWLM",
        "Стрип" to "https://youtu.be/_Z_NA8qqNJs",
        "Дети" to "https://youtu.be/BCmSx8MQlH0",
        "Пати" to "https://youtu.be/CPv7jrco5s0",
        "Варанаси" to "https://youtu.be/PtLESz0UvFY",
        "Мальчик в Balenciaga" to "https://youtu.be/jWlp5HZYhMs",
        "Победоносцев" to "https://youtu.be/vxeKYUuyZsU",
        "Молодой Герцен" to "https://youtu.be/5V1g6K2Z3bU",
        "Grime Vietnam" to "https://youtu.be/wbeu62aVhLY",
        "Калимба" to "https://youtu.be/XEMHeRkC2Vc",
        "Сель" to "https://youtu.be/-AA_K9LWYCI",
        "Ангел Утешения" to "https://youtu.be/Qxx41MCna18",
        "Мы работаем на Кремль" to "https://youtu.be/FQ9okwtYtzw",
        "Дикпик" to "https://youtu.be/bDL3rbaGPh4",
        "Нахапало" to "https://youtu.be/3AT7SHuaPZE",
        "Legends of Cringe" to "https://youtu.be/IhzCqKWXKcA",
        "Дискотека Овсянкин" to "https://youtu.be/zQGlyfUC_cI",
        "Нарцисс" to "https://youtu.be/tYFsQmHIqyA",
        "Jeep" to "https://youtu.be/3dU-6_PmyP4",
        "Окно Овертона" to "https://youtu.be/d4kZ2CgWSbE",
        "Мельтешение жизни" to "https://youtu.be/PrRqRwh59O4",
        "Все мои Ш" to "https://youtu.be/qSPrd-ScjTM",
        "Убили гендер" to "https://youtu.be/9w6yQCghNPY",
        "На свидании с другой" to "https://youtu.be/mIDXV68EV6g",
        "Флекс и флейм" to "https://youtu.be/hwYcX0e0c-c",
        "Подкрадули" to "https://youtu.be/C_zqomMqubg",
        "Жить в кайф" to "https://youtu.be/sJzSYI5fIZE",
        "Губы" to "https://youtu.be/A7M1mYaOfE8",
        "ГДР Music" to "https://youtu.be/GrGs7jreZe0",
        "Лорд П" to "https://youtu.be/htBd4pAVio8",
        "Лоботомия" to "https://youtu.be/NAsbtgWoUFc",
        "По едалу" to "https://youtu.be/dNzP27hxWIk",
        "No hook" to "https://youtu.be/tEG8i4uqJyU",
        "Поминальный свинг" to "https://youtu.be/aBUAeHTXqkw",
        "Sex" to "https://youtu.be/wMnlmrBC2Ec",
        "Hype boyz" to "https://youtu.be/NMn4hRf1Pzw",
        "Айван" to "https://youtu.be/vSxhkARS9vE",
        "Поломанные" to "https://youtu.be/Mh0VqazYwU4",
        "Заторчал" to "https://youtu.be/7U44WNeG6B0",
        "ПТСР-Squad" to "https://youtu.be/dzMiALho3SQ",
        "Белая ворона" to "https://youtu.be/vfwvZv-u0Gk",
        "Молитва" to "https://youtu.be/8cPgoND076g",
        "Гравити Фолз" to "https://youtu.be/RcVdDC4B5mc",
        "Без спецэффектов" to "https://youtu.be/GFA-gVPhBMk",
        "Колл-центр" to "https://youtu.be/MiC1CLOiqvk",
        "Города" to "https://youtu.be/jFcVwUcUIr8",
        "Молодой Грудинин" to "https://youtu.be/_naaClmBSpo",
        "Тучи" to "https://youtu.be/qJ7f9iqmzng",
        "Последний поход" to "https://youtu.be/OY03Kk047xk",
        "Деньги" to "https://youtu.be/sXTqe_u_YVw",
        "Сиротская отрыжка" to "https://youtu.be/odRU1Fms-WE",
        "Сделай мне Grime" to "https://youtu.be/m2BJRKnzReE",
        "Бессонница" to "https://youtu.be/hbC3fEXYEyQ",
        "Котлован" to "https://youtu.be/x_CZDOMPx8Y",
        "TikTok Москвички" to "https://youtu.be/_vZs59y8Uis",
        "Битник" to "https://youtu.be/ZdG0O0OXxps",
        "Сквош" to "https://youtu.be/S32ePE8pv3U",
        "Эффект бабочки" to "https://youtu.be/zevdAb0lqSg",
        "АК" to "https://youtu.be/MYrju5jA0mI",
        "Титаник" to "https://youtu.be/dHoEducjCls",
        "Берег" to "https://youtu.be/_hzU5KPY7G4",
        "Мегаломаны" to "https://youtu.be/DblFAkXHDg4",
        "Ненавижу любовь" to "https://youtu.be/-siLY-CpQcE",
        "Улица слез" to "https://youtu.be/vqTp8O8eLzs",
        "Русский фонк" to "https://youtu.be/KcMtaORY1Fg",
        "Дансинг" to "https://youtu.be/l67Dmy2LEeY",
        "Я пытался" to "https://youtu.be/TXbNuYlC7OM",
        "Кенигсберг" to "https://youtu.be/095EeaBRbOg",
        "Клюв" to "https://youtu.be/ssg3qCwp-7o",
        "Жить в кайф-2" to "https://youtu.be/Ns55CZ-FNHU",
        "Номера" to "https://youtu.be/iPW7aHguX4E",
        "Звук" to "https://youtu.be/7NXOY3Xfv2I",
        "Гобзавр" to "https://youtu.be/VrMakDDVcYc",
        "Гвардейцы Кардинала" to "https://youtu.be/8jtsO28GWVk",
        "Чили" to "https://youtu.be/K-YrYKT8w-s",
        "Дрифт" to "https://youtu.be/RMavMmInUsY",
        "Антихайп Underground" to "https://youtu.be/gOOLZPk8O9k",
        "Все что мне нужно" to "https://youtu.be/W5RJIf4qUi8",
        "Классик" to "https://youtu.be/XQWHSPX0rMw",
        "Зашутился" to "https://youtu.be/yWiUKdmzgrY",
        "Пусть говорят-2" to "https://youtu.be/680MKtMcbv0",
        "Зима-2030" to "https://youtu.be/lqn6iAUv07I",
        "Бридж" to "https://youtu.be/d1NZKYmxpww",
        "Вип" to "https://youtu.be/5_1hTA_b2EM",
        "Старые поэты" to "https://youtu.be/r959u-NSpoo",
        "Тамагочи" to "https://youtu.be/7jTv876Droo",
        "Пустое" to "https://youtu.be/xCEWmQzdFFY",
        "Детка" to "https://youtu.be/mCD6gwnYt_M",
        "Душный" to "https://youtu.be/oudb4YROjKQ",
        "Постирония всерьез" to "https://youtu.be/hN-TPnK8Eow",
        "Виагра" to "https://youtu.be/lWYBJx-WhPk",
        "Замок Антихайпа" to "https://youtu.be/M3qsxnwLO0Q",
        "По России" to "https://youtu.be/uI3N7N_uDDM",
        "Вебкам" to "https://youtu.be/OZFQhsVMkDc",
        "Дао" to "https://youtu.be/pQYEUaKc7TU",
        "В грязи" to "https://youtu.be/fyy6MfU005c",
        "Мечты о падении" to "https://youtu.be/9s500_XH1S4",
        "Трихана" to "https://youtu.be/fFXhr5K-xsA",
        "Прощай Антихайп" to "https://youtu.be/otHGh_PumIA",
        "Antihypeoutro" to "https://youtu.be/FnYQOdRgd0s"
    ).toFavouriteSongs()
}
