package ru.chimchima.repository

object AntihypeRepository : SongRepository {
    override val songs = NemimohypeRepository.songs + HypeTrainRepository.songs + AntihypeTrainRepository.songs
}

object NemimohypeRepository : SongRepository {
    override val songs = listOf(
        "Интро" fav "https://youtu.be/YemQ_lUWR4Y",
        "Трое в лодке (feat. Петрик Путяха)" fav "https://youtu.be/tYQ4vXTboik",
        "Ретвит от Мирона (feat. Букер Д. Фред)" kal "https://youtu.be/6ZQ8eI7jjtM",
        "Берлиоз" fav "https://youtu.be/J6YmF9kSY1A",
        "Надежда Грайма" fav "https://youtu.be/UXr4sxRB0-g",
        "Grime Hate" fav "https://youtu.be/UBRSbL73S-8",
        "Пиу-пиу" kal "https://youtu.be/Ie-3LU06I9w",
        "Контрольный выстрел" fav "https://youtu.be/Z4yaDBnk5G8",
        "Бытиё есть Панчлайн (feat. Вандальский)" kal "https://youtu.be/6KOMWN6HSGc",
        "Умный парень (feat. Vs94ski)" fav "https://youtu.be/2heMxce0ZDc",
        "#НЕМИМОХАЙПА" kal "https://youtu.be/LYW35triFG8",
        "Мой хайп" kal "https://youtu.be/1JjPdns7RCk",
        "Mf Dron (feat. Young Gipsy)" kal "https://youtu.be/-VOu1zyAKEs",
        "Sadwave (feat. Кореш)" kal "https://youtu.be/aKIHE6Ndpj0",
        "Верим в Перуна (Руна нам дана) (feat. Zoo In Space)" kal "https://youtu.be/cK2ZG0bKEk4",
        "Отдыхайте в Крыму! (feat. Вандальский)" kal "https://youtu.be/XAUJpQxQTzw",
        "Не забывай! (feat. Вандальский)" fav "https://youtu.be/tFb4D6WpC-g",
        "Страх и ненависть в Ленинграде" kal "https://youtu.be/BAuDw9mTvXo",
        "Парад калек (feat. MF Док, Саша Маставой & Грязный Луи)" kal "https://youtu.be/z_9E1rX4r4c",
        "ЛГБТ Anthem (feat. ВИА Молодые Аллахи)" kal "https://youtu.be/dsl690CPU_8",
        "Воскресение (feat. Овсянкин)" kal "https://youtu.be/ASFBl5HVJkM",
        "Культурное похмелье (feat. Саша)" kal "https://youtu.be/FVhvcs16tjg",
        "Смерть на рейве" kal "https://youtu.be/_XVnfnkRy40",
        "Апокалипсис" kal "https://youtu.be/zUPMEpTdlcY",
        "Рагнарок (feat. Вандальский)" kal "https://youtu.be/2pMMx4ryGD8",
        "Моя тюрьма (feat. Саша Дискотека)" fav "https://youtu.be/oBh51kpEzBI",
        "Паук (feat. Vs94ski)" fav "https://youtu.be/e2RqDHziN6k",
        "Outro" fav "https://youtu.be/dokLpx5UaA0"
    )
}

object HypeTrainRepository : SongRepository {
    override val songs = listOf(
        "HYPEINTRO" fav "https://youtu.be/jzVuLFXIuJg",
        "Макароны (feat. КИЧ)" fav "https://youtu.be/YaJXdiwXei0",
        "#FREEYUNGTRAPPA (feat. Аббалбиск)" kal "https://youtu.be/iXdvCdR-Lj4",
        "Giger (feat. Аббалбиск)" kal "https://youtu.be/zYwqsf27yV4",
        "Облажает (feat. Unda Scope)" kal "https://youtu.be/Er4mT37feuA",
        "FUCKTRAP (feat. Маки)" fav "https://youtu.be/GhUnTUkM85M",
        "Вейп-вейп-вейп (feat. Лсп, Young P&h, Эхопрокуренныхподъездов, Заебатсу & Booker)" fav "https://youtu.be/dyqbYEQ_a6g",
        "Гоша Рубчинский (feat. Сд, Zoo In Space, Booker & Овсянкин)" fav "https://youtu.be/zYcvQMgxOWU",
        "Сэймяу Game (feat. Овсянкин & Fallen MC)" kal "https://youtu.be/ienV8yg2P1w",
        "Grime в России" kal "https://youtu.be/MtEJEhvSJuY",
        "Сука не нужна (feat. Хип-Хоп Одинокой Старухи & Овсянкин)" kal "https://youtu.be/8wY5HNK04u0",
        "Стикербой (feat. Стеефан)" kal "https://youtu.be/qKROw2UKxL8",
        "Покемоны мои (feat. Монеточка & Овсянкин)" kal "https://youtu.be/kR8Um8DFf-g",
        "Районная (feat. Майти Ди, Edik_Kingsta & Halloween)" kal "https://youtu.be/sMqTfFzeuj8",
        "Вне игры (feat. СД, Саша & Morralles) [Long Mix]" kal "https://youtu.be/wziD6qEi29U",
        "Крокодил (feat. СД, Монк & Овсянкин)" kal "https://youtu.be/rKyf1TSN-5I",
        "Боевой шок (feat. Ленина Пакет)" kal "https://youtu.be/2c77WvotQI8",
        "Корона (feat. Palach)" kal "https://youtu.be/ldq2ydAYDRo",
        "В футболке Бабангида (feat. Овсянкин)" fav "https://youtu.be/YqxL1ONGU_0",
        "Реп-мент (feat. ΨBOY & Человек-Спам)" kal "https://youtu.be/RyQF6f7CD40",
        "Вичхаус лобня-2 (feat. Мц Лучник)" kal "https://youtu.be/E2hrOHiATRU",
        "Дурь-трава (feat. MF Док & Edik_Kingsta)" fav "https://youtu.be/GlcizCN9ztw",
        "Весна (feat. Паша Техник, СД, MF Док & Овсянкин)" kal "https://youtu.be/7zn-muE2sZE",
        "Абамка (feat. Саша Скул & Овсянкин)" kal "https://youtu.be/dqOmJx--BfE",
        "Техника молодежи (feat. Сугат & Некий Шура)" kal "https://youtu.be/SFDRvV1Y1Vs",
        "Сиплота (feat. Сугат, Катровасер & Тот Самый Коля)" kal "https://youtu.be/-0uBovKLTM0",
        "Эльдорадо (feat. Абуя Ко & Саша)" kal "https://youtu.be/rHnRrEzislU",
        "Фонк гука (feat. MF Док)" kal "https://youtu.be/gZ05YMp7CRw",
        "Антихайп (feat. Майти Ди, Zoo In Space & Lokos)" kal "https://youtu.be/evClbzpnQlY",
        "Старый отель (feat. Саша Маставой & Катровасер)" kal "https://youtu.be/_NIEvLE5Ukg"
    )
}

object AntihypeTrainRepository : SongRepository {
    override val songs = listOf(
        "Antihypeintro" fav "https://youtu.be/x0lfEcgjjKE",
        "Двуглавый орёл" fav "https://youtu.be/dh_TPlOFWLM",
        "Стрип" kal "https://youtu.be/_Z_NA8qqNJs",
        "Дети" fav "https://youtu.be/BCmSx8MQlH0",
        "Пати" fav "https://youtu.be/CPv7jrco5s0",
        "Варанаси" fav "https://youtu.be/PtLESz0UvFY",
        "Мальчик в Balenciaga" kal "https://youtu.be/jWlp5HZYhMs",
        "Победоносцев" kal "https://youtu.be/vxeKYUuyZsU",
        "Молодой Герцен" fav "https://youtu.be/5V1g6K2Z3bU",
        "Grime Vietnam" kal "https://youtu.be/wbeu62aVhLY",
        "Калимба" fav "https://youtu.be/XEMHeRkC2Vc",
        "Сель" kal "https://youtu.be/-AA_K9LWYCI",
        "Ангел Утешения" fav "https://youtu.be/Qxx41MCna18",
        "Мы работаем на Кремль" kal "https://youtu.be/FQ9okwtYtzw",
        "Дикпик" kal "https://youtu.be/bDL3rbaGPh4",
        "Нахапало" kal "https://youtu.be/3AT7SHuaPZE",
        "Legends of Cringe" kal "https://youtu.be/IhzCqKWXKcA",
        "Дискотека Овсянкин" fav "https://youtu.be/zQGlyfUC_cI",
        "Нарцисс" kal "https://youtu.be/tYFsQmHIqyA",
        "Jeep" fav "https://youtu.be/3dU-6_PmyP4",
        "Окно Овертона" fav "https://youtu.be/d4kZ2CgWSbE",
        "Мельтешение жизни" fav "https://youtu.be/PrRqRwh59O4",
        "Все мои Ш" kal "https://youtu.be/qSPrd-ScjTM",
        "Убили гендер" fav "https://youtu.be/9w6yQCghNPY",
        "На свидании с другой" kal "https://youtu.be/mIDXV68EV6g",
        "Флекс и флейм" fav "https://youtu.be/bDM-AWBJaS0",
        "Подкрадули" fav "https://youtu.be/C_zqomMqubg",
        "Жить в кайф" fav "https://youtu.be/sJzSYI5fIZE",
        "Губы" kal "https://youtu.be/A7M1mYaOfE8",
        "ГДР Music" kal "https://youtu.be/GrGs7jreZe0",
        "Лорд П" fav "https://youtu.be/htBd4pAVio8",
        "Лоботомия" fav "https://youtu.be/NAsbtgWoUFc",
        "По едалу" kal "https://youtu.be/dNzP27hxWIk",
        "No hook" kal "https://youtu.be/tEG8i4uqJyU",
        "Поминальный свинг" fav "https://youtu.be/aBUAeHTXqkw",
        "Sex" kal "https://youtu.be/wMnlmrBC2Ec",
        "Hype boyz" kal "https://youtu.be/NMn4hRf1Pzw",
        "Айван" fav "https://youtu.be/vSxhkARS9vE",
        "Поломанные" fav "https://youtu.be/Mh0VqazYwU4",
        "Заторчал" kal "https://youtu.be/7U44WNeG6B0",
        "ПТСР-Squad" kal "https://youtu.be/dzMiALho3SQ",
        "Белая ворона" kal "https://youtu.be/vfwvZv-u0Gk",
        "Молитва" kal "https://youtu.be/8cPgoND076g",
        "Гравити Фолз" kal "https://youtu.be/RcVdDC4B5mc",
        "Без спецэффектов" kal "https://youtu.be/GFA-gVPhBMk",
        "Колл-центр" kal "https://youtu.be/MiC1CLOiqvk",
        "Города" kal "https://youtu.be/jFcVwUcUIr8",
        "Молодой Грудинин" kal "https://youtu.be/_naaClmBSpo",
        "Тучи" fav "https://youtu.be/qJ7f9iqmzng",
        "Последний поход" kal "https://youtu.be/OY03Kk047xk",
        "Деньги" fav "https://youtu.be/sXTqe_u_YVw",
        "Сиротская отрыжка" fav "https://youtu.be/odRU1Fms-WE",
        "Сделай мне Grime" kal "https://youtu.be/m2BJRKnzReE",
        "Бессонница" kal "https://youtu.be/hbC3fEXYEyQ",
        "Котлован" fav "https://youtu.be/x_CZDOMPx8Y",
        "TikTok Москвички" kal "https://youtu.be/_vZs59y8Uis",
        "Битник" kal "https://youtu.be/ZdG0O0OXxps",
        "Сквош" kal "https://youtu.be/S32ePE8pv3U",
        "Эффект бабочки" kal "https://youtu.be/zevdAb0lqSg",
        "АК" kal "https://youtu.be/MYrju5jA0mI",
        "Титаник" kal "https://youtu.be/dHoEducjCls",
        "Берег" kal "https://youtu.be/_hzU5KPY7G4",
        "Мегаломаны" kal "https://youtu.be/DblFAkXHDg4",
        "Ненавижу любовь" fav "https://youtu.be/-siLY-CpQcE",
        "Улица слез" kal "https://youtu.be/vqTp8O8eLzs",
        "Русский фонк" kal "https://youtu.be/KcMtaORY1Fg",
        "Дансинг" kal "https://youtu.be/l67Dmy2LEeY",
        "Я пытался" fav "https://youtu.be/TXbNuYlC7OM",
        "Кенигсберг" kal "https://youtu.be/095EeaBRbOg",
        "Клюв" kal "https://youtu.be/ssg3qCwp-7o",
        "Жить в кайф-2" kal "https://youtu.be/Ns55CZ-FNHU",
        "Номера" fav "https://youtu.be/iPW7aHguX4E",
        "Звук" fav "https://youtu.be/7NXOY3Xfv2I",
        "Гобзавр" kal "https://youtu.be/VrMakDDVcYc",
        "Гвардейцы Кардинала" kal "https://youtu.be/8jtsO28GWVk",
        "Чили" kal "https://youtu.be/K-YrYKT8w-s",
        "Дрифт" kal "https://youtu.be/RMavMmInUsY",
        "Антихайп Underground" kal "https://youtu.be/gOOLZPk8O9k",
        "Все что мне нужно" kal "https://youtu.be/W5RJIf4qUi8",
        "Классик" kal "https://youtu.be/XQWHSPX0rMw",
        "Зашутился" kal "https://youtu.be/yWiUKdmzgrY",
        "Пусть говорят-2" fav "https://youtu.be/680MKtMcbv0",
        "Зима-2030" fav "https://youtu.be/lqn6iAUv07I",
        "Бридж" kal "https://youtu.be/d1NZKYmxpww",
        "Вип" kal "https://youtu.be/5_1hTA_b2EM",
        "Старые поэты" kal "https://youtu.be/r959u-NSpoo",
        "Тамагочи" fav "https://youtu.be/7jTv876Droo",
        "Пустое" kal "https://youtu.be/xCEWmQzdFFY",
        "Детка" kal "https://youtu.be/mCD6gwnYt_M",
        "Душный" kal "https://youtu.be/oudb4YROjKQ",
        "Постирония всерьез" kal "https://youtu.be/hN-TPnK8Eow",
        "Виагра" fav "https://youtu.be/lWYBJx-WhPk",
        "Замок Антихайпа" kal "https://youtu.be/M3qsxnwLO0Q",
        "По России" fav "https://youtu.be/uI3N7N_uDDM",
        "Вебкам" fav "https://youtu.be/OZFQhsVMkDc",
        "Дао" kal "https://youtu.be/pQYEUaKc7TU",
        "В грязи" kal "https://youtu.be/fyy6MfU005c",
        "Мечты о падении" fav "https://youtu.be/9s500_XH1S4",
        "Трихана" fav "https://youtu.be/fFXhr5K-xsA",
        "Прощай Антихайп" fav "https://youtu.be/otHGh_PumIA",
        "Antihypeoutro" fav "https://youtu.be/FnYQOdRgd0s"
    )
}
