package ru.chimchima.repository

object AntihypeRepository : SongRepository {
    override val songs = NemimohypeRepository.songs + HypeTrainRepository.songs + AntihypeTrainRepository.songs
}

object NemimohypeRepository : SongRepository {
    override val songs = listOf(
        "Интро" fav "https://youtu.be/YemQ_lUWR4Y",
        "Трое в лодке (feat. Петрик Путяха)" fav "https://youtu.be/tYQ4vXTboik",
        "Ретвит от Мирона (feat. Букер Д. Фред)" kal "https://youtu.be/6ZQ8eI7jjtM",
        "Берлиоз" fav "https://youtu.be/J6YmF9kSY1A",
        "Надежда Грайма" fav "https://youtu.be/UXr4sxRB0-g",
        "Grime Hate" fav "https://youtu.be/UBRSbL73S-8",
        "Пиу-пиу" kal "https://youtu.be/Ie-3LU06I9w",
        "Контрольный выстрел" fav "https://youtu.be/Z4yaDBnk5G8",
        "Бытиё есть Панчлайн (feat. Вандальский)" kal "https://youtu.be/6KOMWN6HSGc",
        "Умный парень (feat. Vs94ski)" fav "https://youtu.be/2heMxce0ZDc",
        "#НЕМИМОХАЙПА" kal "https://youtu.be/LYW35triFG8",
        "Мой хайп" kal "https://youtu.be/1JjPdns7RCk",
        "Mf Dron (feat. Young Gipsy)" kal "https://youtu.be/-VOu1zyAKEs",
        "Sadwave (feat. Кореш)" kal "https://youtu.be/aKIHE6Ndpj0",
        "Верим в Перуна (Руна нам дана) (feat. Zoo In Space)" kal "https://youtu.be/cK2ZG0bKEk4",
        "Отдыхайте в Крыму! (feat. Вандальский)" kal "https://youtu.be/XAUJpQxQTzw",
        "Не забывай! (feat. Вандальский)" fav "https://youtu.be/tFb4D6WpC-g",
        "Страх и ненависть в Ленинграде" kal "https://youtu.be/BAuDw9mTvXo",
        "Парад калек (feat. MF Док, Саша Маставой & Грязный Луи)" kal "https://youtu.be/z_9E1rX4r4c",
        "ЛГБТ Anthem (feat. ВИА Молодые Аллахи)" kal "https://youtu.be/dsl690CPU_8",
        "Воскресение (feat. Овсянкин)" kal "https://youtu.be/ASFBl5HVJkM",
        "Культурное похмелье (feat. Саша)" kal "https://youtu.be/FVhvcs16tjg",
        "Смерть на рейве" kal "https://youtu.be/_XVnfnkRy40",
        "Апокалипсис" kal "https://youtu.be/zUPMEpTdlcY",
        "Рагнарок (feat. Вандальский)" kal "https://youtu.be/2pMMx4ryGD8",
        "Моя тюрьма (feat. Саша Дискотека)" fav "https://youtu.be/oBh51kpEzBI",
        "Паук (feat. Vs94ski)" fav "https://youtu.be/e2RqDHziN6k",
        "Outro" fav "https://youtu.be/dokLpx5UaA0"
    )
}

object HypeTrainRepository : SongRepository {
    override val songs = listOf(
        "HYPEINTRO" fav "https://youtu.be/jzVuLFXIuJg",
        "Макароны (feat. КИЧ)" fav "https://youtu.be/YaJXdiwXei0",
        "#FREEYUNGTRAPPA (feat. Аббалбиск)" kal "https://youtu.be/iXdvCdR-Lj4",
        "Giger (feat. Аббалбиск)" kal "https://youtu.be/zYwqsf27yV4",
        "Облажает (feat. Unda Scope)" kal "https://youtu.be/Er4mT37feuA",
        "FUCKTRAP (feat. Маки)" fav "https://youtu.be/GhUnTUkM85M",
        "Вейп-вейп-вейп (feat. Лсп, Young P&h, Эхопрокуренныхподъездов, Заебатсу & Booker)" fav "https://youtu.be/dyqbYEQ_a6g",
        "Гоша Рубчинский (feat. Сд, Zoo In Space, Booker & Овсянкин)" fav "https://youtu.be/zYcvQMgxOWU",
        "Сэймяу Game (feat. Овсянкин & Fallen MC)" kal "https://youtu.be/ienV8yg2P1w",
        "Grime в России" kal "https://youtu.be/MtEJEhvSJuY",
        "Сука не нужна (feat. Хип-Хоп Одинокой Старухи & Овсянкин)" kal "https://youtu.be/8wY5HNK04u0",
        "Стикербой (feat. Стеефан)" kal "https://youtu.be/qKROw2UKxL8",
        "Покемоны мои (feat. Монеточка & Овсянкин)" kal "https://youtu.be/kR8Um8DFf-g",
        "Районная (feat. Майти Ди, Edik_Kingsta & Halloween)" kal "https://youtu.be/sMqTfFzeuj8",
        "Вне игры (feat. СД, Саша & Morralles) [Long Mix]" kal "https://youtu.be/wziD6qEi29U",
        "Крокодил (feat. СД, Монк & Овсянкин)" kal "https://youtu.be/rKyf1TSN-5I",
        "Боевой шок (feat. Ленина Пакет)" kal "https://youtu.be/2c77WvotQI8",
        "Корона (feat. Palach)" kal "https://youtu.be/ldq2ydAYDRo",
        "В футболке Бабангида (feat. Овсянкин)" fav "https://youtu.be/YqxL1ONGU_0",
        "Реп-мент (feat. ΨBOY & Человек-Спам)" kal "https://youtu.be/RyQF6f7CD40",
        "Вичхаус лобня-2 (feat. Мц Лучник)" kal "https://youtu.be/E2hrOHiATRU",
        "Дурь-трава (feat. MF Док & Edik_Kingsta)" fav "https://youtu.be/GlcizCN9ztw",
        "Весна (feat. Паша Техник, СД, MF Док & Овсянкин)" kal "https://youtu.be/7zn-muE2sZE",
        "Абамка (feat. Саша Скул & Овсянкин)" kal "https://youtu.be/dqOmJx--BfE",
        "Техника молодежи (feat. Сугат & Некий Шура)" kal "https://youtu.be/SFDRvV1Y1Vs",
        "Сиплота (feat. Сугат, Катровасер & Тот Самый Коля)" kal "https://youtu.be/-0uBovKLTM0",
        "Эльдорадо (feat. Абуя Ко & Саша)" kal "https://youtu.be/rHnRrEzislU",
        "Фонк гука (feat. MF Док)" kal "https://youtu.be/gZ05YMp7CRw",
        "Антихайп (feat. Майти Ди, Zoo In Space & Lokos)" kal "https://youtu.be/evClbzpnQlY",
        "Старый отель (feat. Саша Маставой & Катровасер)" kal "https://youtu.be/_NIEvLE5Ukg"
    )
}

object AntihypeTrainRepository : SongRepository {
    override val songs = listOf(
        "Antihypeintro" fav "https://youtu.be/FAUcfUxTOMo",
        "Двуглавый орёл" fav "https://youtu.be/dh_TPlOFWLM",
        "Стрип" kal "https://youtu.be/UCEpluTZru4",
        "Дети" fav "https://youtu.be/vn8c7LPLV2o",
        "Пати" fav "https://youtu.be/CPv7jrco5s0",
        "Варанаси" fav "https://youtu.be/p-6RrWBYqNs",
        "Мальчик в Balenciaga" kal "https://youtu.be/BT4taix8CAQ",
        "Победоносцев" kal "https://youtu.be/2jknTVFjGo4",
        "Молодой Герцен" fav "https://youtu.be/vnLqU2e0ltY",
        "Grime Vietnam" kal "https://youtu.be/D2M1Ek9XUFs",
        "Калимба" fav "https://youtu.be/marJB7aVJYs",
        "Сель" kal "https://youtu.be/zt2UB57l_Fc",
        "Ангел Утешения" fav "https://youtu.be/ZpQb-mmxenM",
        "Мы работаем на Кремль" kal "https://youtu.be/FQ9okwtYtzw",
        "Дикпик" kal "https://youtu.be/h-ZyCoXM27o",
        "Нахапало" kal "https://youtu.be/352aq17ssC0",
        "Legends of Cringe" kal "https://youtu.be/st-Vz_63QSc",
        "Дискотека Овсянкин" fav "https://youtu.be/zQGlyfUC_cI",
        "Нарцисс" kal "https://youtu.be/sJ0P8_oDW_0",
        "Jeep" fav "https://youtu.be/GHEU9CqAWpI",
        "Окно Овертона" fav "https://youtu.be/fQ76dLcZarY",
        "Мельтешение жизни" fav "https://youtu.be/zATqunuzQ08",
        "Все мои Ш" kal "https://youtu.be/0V9HU1DBp64",
        "Убили гендер" fav "https://youtu.be/_O41VoTdw7I",
        "На свидании с другой" kal "https://youtu.be/j4qU9HlAMto",
        "Флекс и флейм" fav "https://youtu.be/hwYcX0e0c-c",
        "Подкрадули" fav "https://youtu.be/ssEgJ3mtW2s",
        "Жить в кайф" fav "https://youtu.be/qoWlsFDeGfc",
        "Губы" kal "https://youtu.be/A7M1mYaOfE8",
        "ГДР Music" kal "https://youtu.be/e7eXUvpm2VE",
        "Лорд П" fav "https://youtu.be/yDcO560ePUA",
        "Лоботомия" fav "https://youtu.be/RHay65nuW98",
        "По едалу" kal "https://youtu.be/sxf0JHweT0M",
        "No hook" kal "https://youtu.be/8tp4CprDIjQ",
        "Поминальный свинг" fav "https://youtu.be/aBUAeHTXqkw",
        "Sex" kal "https://youtu.be/o8UiUNBU0IU",
        "Hype boyz" kal "https://youtu.be/3NUVE5N_3FU",
        "Айван" fav "https://youtu.be/efiWXMXD4rs",
        "Поломанные" fav "https://youtu.be/28baQ90YGPI",
        "Заторчал" kal "https://youtu.be/_osqWgiKrHQ",
        "ПТСР-Squad" kal "https://youtu.be/3WfPofnBERM",
        "Белая ворона" kal "https://youtu.be/wqOowcFDqQU",
        "Молитва" kal "https://youtu.be/4iknN6kSvYs",
        "Гравити Фолз" kal "https://youtu.be/R6fDxQrE12I",
        "Без спецэффектов" kal "https://youtu.be/G_gK6TCcK78",
        "Колл-центр" kal "https://youtu.be/hhgHq5cJVVo",
        "Города" kal "https://youtu.be/G8_zwxwg2yY",
        "Молодой Грудинин" kal "https://youtu.be/fIR_iRIu0oI",
        "Тучи" fav "https://youtu.be/Fe3uanrGTQE",
        "Последний поход" kal "https://youtu.be/t4jC-ZX6x1Y",
        "Деньги" fav "https://youtu.be/53UYis5HBVU",
        "Сиротская отрыжка" fav "https://youtu.be/0w1FhR195qE",
        "Сделай мне Grime" kal "https://youtu.be/CWyFI8fq4pk",
        "Бессонница" kal "https://youtu.be/VqjOufJYam4",
        "Котлован" fav "https://youtu.be/e7v5q0jHKgc",
        "TikTok Москвички" kal "https://youtu.be/8DosC1mxwN8",
        "Битник" kal "https://youtu.be/-j9Ok5MHtuU",
        "Сквош" kal "https://youtu.be/uwODVmhJb-s",
        "Эффект бабочки" kal "https://youtu.be/ZGZWiXbOwIg",
        "АК" kal "https://youtu.be/phrLZ6hoIb0",
        "Титаник" kal "https://youtu.be/zjWPaXiXQPY",
        "Берег" kal "https://youtu.be/y40AufRJ7HM",
        "Мегаломаны" kal "https://youtu.be/_Rw5H_Jhtec",
        "Ненавижу любовь" fav "https://youtu.be/jn9Oy-a-MLU",
        "Улица слез" kal "https://youtu.be/loUtnnqjIyg",
        "Русский фонк" kal "https://youtu.be/AoGCeQKBa5w",
        "Дансинг" kal "https://youtu.be/UZWCMBYVRzk",
        "Я пытался" fav "https://youtu.be/H1PzRFmik78",
        "Кенигсберг" kal "https://youtu.be/7MfgJwqMMfo",
        "Клюв" kal "https://youtu.be/00BBauSZXLM",
        "Жить в кайф-2" kal "https://youtu.be/0oIYxhQZALE",
        "Номера" fav "https://youtu.be/cdZLZzYZP64",
        "Звук" fav "https://youtu.be/FIJKjHlVX-k",
        "Гобзавр" kal "https://youtu.be/SmvtMHkLUJo",
        "Гвардейцы Кардинала" kal "https://youtu.be/jl0cxDzefpQ",
        "Чили" kal "https://youtu.be/zqWet28qtKc",
        "Дрифт" kal "https://youtu.be/pJkWTEEy0iA",
        "Антихайп Underground" kal "https://youtu.be/P43mfkhO53M",
        "Все что мне нужно" kal "https://youtu.be/9uzyk2xbKCY",
        "Классик" kal "https://youtu.be/hMC7CUKvxEc",
        "Зашутился" kal "https://youtu.be/EwjjAoUbzlw",
        "Пусть говорят-2" fav "https://youtu.be/xoXhst0vFhM",
        "Зима-2030" fav "https://youtu.be/DNR4iggt4C8",
        "Бридж" kal "https://youtu.be/Kk5iczsdI1Q",
        "Вип" kal "https://youtu.be/l0lqRiodG9I",
        "Старые поэты" kal "https://youtu.be/BmUh2jFsDcs",
        "Тамагочи" fav "https://youtu.be/YWt0FmT_Lic",
        "Пустое" kal "https://youtu.be/jmwraR8Ggmw",
        "Детка" kal "https://youtu.be/_T3PzGWhWDk",
        "Душный" kal "https://youtu.be/GJG54vnFyxM",
        "Постирония всерьез" kal "https://youtu.be/Gj7nBVCYr6Y",
        "Виагра" fav "https://youtu.be/-Jb0p5zILdM",
        "Замок Антихайпа" kal "https://youtu.be/wzzb43GuLeI",
        "По России" fav "https://youtu.be/Q-mrVDfRwuA",
        "Вебкам" fav "https://youtu.be/X_DpYubsEIY",
        "Дао" kal "https://youtu.be/0rcB3Wj0UPU",
        "В грязи" kal "https://youtu.be/si8XIAbDLTA",
        "Мечты о падении" fav "https://youtu.be/g5PzrAXKrzI",
        "Трихана" fav "https://youtu.be/0U7diGch4Xc",
        "Прощай Антихайп" fav "https://youtu.be/BReiHwIdycU",
        "Antihypeoutro" fav "https://youtu.be/rJHdbzqhMpw"
    )
}
